apiVersion: v1
kind: Pod
metadata:
  name: shared-volume-pod
spec:
  containers:
  - image: busybox
    name: busybox1
    command: ['sh','-c','while true; do echo success > /output/success.txt; sleep 5; done']
    volumeMounts:
    - mountPath: /output
      name: test-volume
  - image: busybox
    name: busybox2
    command: ['sh','-c','while true; do cat /input/success.txt; sleep 5; done']
    volumeMounts:
    - mountPath: /input
      name: test-volume
  volumes:
  - name: test-volume
    emptyDir: {}
