apiVersion: v1
kind: Pod
metadata:
  name: my-volume-pod
spec:
  containers:
  - image: busybox
    name: busybox
    command: ['sh','-c','while true; do echo success > /output/success.txt; done']
    volumeMounts:
    - mountPath: /output
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /var/data
