apiVersion: v1
kind: Pod
metadata:
  name: multi-container-playground     
spec:
  restartPolicy: Never
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: c1
    image: nginx:1.17.6-alpine
    env:
    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  - name: c2
    image: busybox:1.31.1
    volumeMounts:
    - name: shared-data
      mountPath: /c2
    command: ["/bin/sh"]
    args: ["-c", "while true; do date >> /c2/date.log; sleep 1; done"]
  - name: c3
    image: busybox:1.31.1
    volumeMounts:
    - name: shared-data
      mountPath: /c3
    command: ["sh","-c", "tail -f /c3/date.log"]
