apiVersion: v1
kind: Service
metadata:
  name: svc-nodeport
spec:
  type: NodePort # This allows the communication from outside the cluster
  selector:
    app: svc-example #to which pod the service is attached to by the labels
  ports:
    - protocol: TCP
      port: 80 # to where the client communicates with the service 
      targetPort: 80 # where the service routes the request to, in this case pod listens to port 80
      nodePort: 30080 #where the service listens on the all nodes, control plane and workers. 
