apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
spec:
  containers:
    - name: nginx-test
      image: nginx:1.19.1
      ports:
        - containerPort: 80
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/nginx/conf
        - name: config-volume
          mountPath: /etc/nginx
  # The secret data is exposed to Containers in the Pod through a Volume.
  volumes:
    - name: secret-volume
      secret:
        secretName: nginx-htpasswd
        volumes:
    - name: config-volume
      configMap:
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
        name: nginx-config

