apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  initContainers:
  - name: init-delay
    image: busybox:1.28
    command: ['sleep','30']
