apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  # secretkey1: secret | base64
  secretkey1: c2VjcmV0Cg== 
  # secretkey1: another secret | base64
  secretkey2: YW5vdGhlciBzZWNyZXQK
