apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh','-c','while true;do sleep 3600; done']
    volumeMounts:
    - name: my-configmap-volume
      mountPath: /etc/config/configmap
    - name: my-secret-volume
      mountPath: /etc/config/secret
  volumes:
  - name: my-configmap-volume
    configMap:
    # Provide the name of the ConfigMap containing the files you want to add to the container
      name: my-configmap
  - name: my-secret-volume
    secret:
      secretName: my-secret

