apiVersion: v1
kind: Pod
metadata:
  name: big-request-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh','-c','while true; do sleep 3600; done']
    resources:
      requests:
        memory: "128Mi"
        #10 cpus's
        cpu: "10000m"
