apiVersion: v1
kind: Pod
metadata:
  name: resource-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh','-c','while true; do sleep 3600; done']
    resources:
      requests:
        memory: "128Mi"
        #2,5 cpus's
        cpu: "250m"
      limits: 
        #if container exceeds memory limit, it gets killed 
        memory: "256Mi"
        # container exceeds cpu limit, gets .. but not killed
        cpu: "500m"
