apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-data
  namespace: beebox-auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-data
  template:
    metadata:
      labels:
        app: auth-data
    spec:
      nodeSelector:
        auth: "true" #true must be in quotes so it wont be mistaken as boolean by k8s
      containers:
      - name: nginx
        image: nginx:1.19.1
        ports:
        - containerPort: 80
