apiVersion: v1
kind: Pod
metadata:
  name: auth-gateway
  namespace: beebox-auth
spec:
  nodeName: k8s-worker2
  containers:
  - name: nginx
    image: nginx:1.19.1
    ports:
    - containerPort: 80

