apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  restartPolicy: Never
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: busybox-dump1ogs
    image: busybox
    command: ['sh','-c','while true; do echo dump logs > /output/logs.txt; done']
    volumeMounts:
    - name: shared-data
      mountPath: /output
  - name: busybox-readlogs
    image: busybox
    volumeMounts:
    - name: shared-data
      mountPath: /input
    command: ["/bin/sh",'-c','tail -f /input/logs.txt ']
